### ISSUE TITLE
Roof running game keeps refreshing and saying 'failed' [BUG]

### ISSUE THREAD

**Issue by klydeinside** [MaximilianAdF/NoPixel-MiniGames-4.0#22]
https://github.com/MaximilianAdF/NoPixel-MiniGames-4.0/assets/37005235/e26f39e6-92f3-4c10-a25e-2f3da91efa98

I played this the other day for a long time and it never did this. I'm not sure what's happening. When I first played it, I played it on a browser full of extensions with no issues. I tried the same browser and also a browser with 0 extensions installed. Also tried private mode. It just keeps doing this.

**Comment by MaximilianAdF** [comment]
The game you showed have become unsolvable after the clicks that you have performed. Since there's no solution it automatically ends the game

As an illustration here's how it would go in the first game (r = red, b = blue, g=green)
| r| | | | |
|-----|-----|-----|-----|-----| 
| g| b| g| | |
| b| b| g| r| |
| b| r| r| g| b|
| r| r| r| b| b|

* **Click on red** *
The game will look like this:

|‎‎&nbsp; | | | | |
|-----|-----|-----|-----|-----| 
| r| | | | |
| g| r| | | |
| b| b| g| g| b|
| b| b| g| b| b|

* **Click on bottom left blues** *

|&nbsp; | | | | |
|-----|-----|-----|-----|-----| 
|&nbsp; | | | | |
|&nbsp; | | | | |
| r| g| g| b| |
| g| r| g| b| b|

As you can see there's a green cornered in the bottom left corner that will never be possible to remove. All possible combinations are tested when these automatic fails are performed.

Although I did notice that the second game you played actually did have a solution, I will look into this case and see what's causing the false positive.

**Comment by MaximilianAdF** [comment]
checkSolvable() function not working correctly

**Comment by MaximilianAdF** [comment]
False positives have been fixed now
