### ISSUE TITLE
[BUG] Roof Running - Inconsistent fail & success detection

### ISSUE THREAD

**Issue by sethwalker1** [MaximilianAdF/NoPixel-MiniGames-4.0#25]
**Describe the bug**
Sometimes a game is terminated while it is still solvable. Sometimes it is not terminated after becoming unsolvable.

**To Reproduce**
Unclear what exactly causes it, but it seems to be an issue with single blocks.

**Screenshots**
Unsolvable puzzle not terminating:
![image](https://github.com/MaximilianAdF/NoPixel-MiniGames-4.0/assets/13321574/5da9ec82-887e-4bc5-bf6b-06519813377a)
Solvable puzzle terminating:
![image](https://github.com/MaximilianAdF/NoPixel-MiniGames-4.0/assets/13321574/2038cff3-f583-4e09-81a1-ffbc411fda8d)

**Comment by BobDotCom** [comment]
@MaximilianAdF 
I did some debugging on this, and I came to a couple conclusions. I didn't find a complete fix for any of it, but I figured I'd share my findings, so hopefully it's helpful.

The `checkSolvable` function has a few flaws:
1. It only seems to check the first possible route. So every time, you can continue clicking the top-left group (the group with the lowest index) and it will always lead to a solved board because of this issue in the algorithm.
2. After fixing that issue, I learned that there was a second problem. For some reason, `checkSolvable` has a hard time when applying the down/left gravity (`cubesUpdate`). It doesn't seem to realize that the blocks will be moved next to each other after the gravity is applied.

Also, I think during the puzzle instead of calling `checkSolvable()` each time, there should be a second method `shouldFail()` which only runs the "single" of a certain color check. That way, it's clearer to the user when they've failed, instead of just telling them right away. 


My two cents:

From a personal standpoint, I think it would be more effective to store the board as custom objects in memory and not rely on the DOM state for updates. I've found a couple weird bugs where I can click an empty space, and it registers a click for a random block. Since you're clearing and re-writing the DOM for the board each update anyway, storing the entire board state in JavaScript wouldn't be less efficient, plus IMO would be easier to maintain and prevent bugs like this.

**Comment by sethwalker1** [comment]
+1 to managing the state of the puzzle in memory! I like the idea of the DOM simply being a reflection of the true state of the puzzle.

As for checking the solvability of the puzzle, I'd suggest checking if there are any connected cubes and failing upon reaching 0.

1. This approach is less complex and more reliable.
2. NoPixel already handles the hack this way, so it would better reflect the hack we're mimicking here.

**Comment by BobDotCom** [comment]
> As for checking the solvability of the puzzle, I'd suggest checking if there are any connected cubes and failing upon reaching 0.
+1, that's what I was thinking when I suggested the addition of a `shouldFail()` method. Since it's handled that way on NoPixel, it just makes more sense. Maybe it should also check if there's a singular block of one color, since that's an easily-detectable failure as well. (and afaik, NoPixel handles this as well)

I still think a `checkSolvable()` method could be useful to determine if a starting board is solvable. However, like you mentioned, the chances of an unsolvable board with the increased size are unlikely enough that this likely isn't necessary. Maybe it could be removed for now, and revisited if they reduce the size of the puzzle again.

**Comment by BobDotCom** [comment]
I've just pushed a PR that implements the `shouldFail()` method with a couple of other changes too.

I didn't change anything with the DOM yet, that would be a much larger change and may require more discussion.

**Comment by MaximilianAdF** [comment]
Great work on the `shouldFail()`. Definitely in need of some simpler approach than the current `checkSolvable()`, might have to remove it altogether if it becomes too problematic.

I really like the idea of keeping the board in memory. Just like you, @BobDotCom, I've encountered some weird situations seemingly caused by the fetching, clearing, re-writing etc. of the DOM state. Although, I have never got around to thinking of an alternate approach to solving the previous. In the future I think it's definitely a worthwhile implementation, especially as the board's size increases.
